
---
swagger: '2.0'
info:
  title: Bank Argent API Transaction documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/operations:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transactions
      description: API for monthly transactions
      parameters:
        - in: body
          name: body
          description: Transactions Payload
          required: true
          schema:
            $ref: '#/definitions/TransactionsList'
      produces:
        - application/json
      responses:
        '200':
          description: Transactions shown with success
          schema:
            $ref: '#/definitions/TransactionsList'
        '400':
          description: Cannot get transactions
        '500':
          description: Internal Server Error
  /user/operation/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transaction
      description: API for transaction
      parameters:
        - name: id
          in: path
          description: ID of the operation
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Transaction detail Payload
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Got operation Successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Cannot get operation
        '500':
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Adding information to transaction  API
      description: API for adding information for user transaction
      parameters:
        - name: id
          in: path
          description: ID of the operation
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Transaction detail Payload
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Cannot get operation
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
       - Transactions Module
      summary: Modifying information of transaction
      description: API for transaction
      parameters:
        - name: id
          in: path
          description: ID of the operation
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Transaction detail Payload
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Cannot get operation
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
       - Transactions Module
      summary: Deleting transaction
      description: API for transaction
      parameters:
        - name: id
          in: path
          description: ID of the operation
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Transaction detail Payload
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Cannot get operation
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionsList:
    properties: 
      transaction 1:
        type: object
        description: transaction list
        properties:
          id:
            type: number
            description: transaction id
          title:
            type: string
            description: transaction title
          balance:
            type: number
            description: transaction balance
          balanceTypeDescription:
            type: string
            description: type of balance - current or avaliable
      transaction 2:
        type: object
        description: transaction list
        properties:
          id:
            type: number
            description: transaction id
          title:
            type: string
            description: transaction title
          balance:
            type: number
            description: transaction balance
          balanceTypeDescription:
            type: string
            description: type of balance - current or avaliable
  Transaction:
    properties:
      id:
        type: number
        description: transaction id
      date:
        type: string
        description: transaction date
      description:
          type: string
          description: transaction description
      amount:
        type: number
        description: transaction amount
      balance:
        type: number
        description: transaction balance
      details:
        type: object
        description: transaction details
        properties:
          type:
            type: string
            description: transaction type
          category:
            type: string
            description: transaction category
          note:
            type: string
            description: transaction note