
---
swagger: '2.0'
info:
  title: Bank Argent API Transaction documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/operations:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transactions
      description: API for monthly transactions
      parameters:
        - in: body
          name: body
          description: Transactions Payload
          required: true
          schema:
            $ref: '#/definitions/TransactionsList'
      produces:
        - application/json
      responses:
        '200':
          description: Transactions shown with success
          schema:
            $ref: '#/definitions/TransactionsList'
        '400':
          description: Cannot get transactions
        '500':
          description: Internal Server Error
  /user/operation/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transaction detail
      description: API for transaction detail
      parameters:
        - name: id
          in: path
          description: ID of the operation
          required: true
          type: integer
          format: int64
          schema:
            $ref: '#/definitions/TransactionDetail'
      produces:
        - application/json
      responses:
        '200':
          description: Got operation Successfully
          schema:
            $ref: '#/definitions/TransactionDetail'
        '400':
          description: Cannot get operation
        '500':
          description: Internal Server Error
  /user/operation/{trId}:
    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Adding information to transaction  API
      description: API for adding information for user transaction
      parameters:
        - name: trId
          in: path
          description: ID of the operation
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Transaction detail Payload
          required: true
          schema:
            $ref: '#/definitions/TransactionDetail'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/TransactionDetail'
        '400':
          description: Cannot get operation
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
       - Transactions Module
      summary: Modifying information of transaction
      description: API for transaction
      parameters:
        - in: body
          name: body
          description: Transaction detail Payload
          required: true
          schema:
            $ref: '#/definitions/TransactionDetail'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/TransactionDetail'
        '400':
          description: Cannot get operation
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
       - Transactions Module
      summary: Deleting transaction
      description: API for transaction
      parameters:
        - in: body
          name: body
          description: Transaction detail Payload
          required: true
          schema:
            $ref: '#/definitions/TransactionDetail'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/TransactionDetail'
        '400':
          description: Cannot get operation
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionsList:
    properties:
      transactions:
        type: array
        description: transaction list
  TransactionDetail:
    properties:
      title:
        type: string
        description: transaction title
      amount:
        type: string
        description: transaction amount
      description:
        type: string
        description: transaction description
     



